### ISSUE TITLE
Problems compiling - Linux and Arduino IDE 1.8.6 

### ISSUE THREAD

**Issue by equake** [evert-arias/EasyBuzzer#3]
Hi! 
Can't make EasyBuzzer work.
```
In file included from /tmp/arduino_modified_sketch_296664/Sequence.ino:8:0:
./Arduino/libraries/EasyBuzzer/src/EasyBuzzer.h:14:22: fatal error: arduino.h: No such file or directory
compilation terminated.
exit status 1
```
Files names are case sensitive in Linux, maybe you should include "Arduino.h"?

Thanks!

**Comment by evert-arias** [comment]
@equake Hi,
It's done!
https://github.com/evert-arias/EasyBuzzer/commit/2cf10b8be09abe2a0d5c76ea3f4549e5811e7057

Thanks for the feedback.
