### ISSUE TITLE
Does not work on Mega

### ISSUE THREAD

**Issue by mvackel** [evert-arias/EasyBuzzer#6]
The lib seems to be directed to Atmega328 and ESP8266/32. It does not work on Mega2560.
To make it more general, I suggest the following change:
&nbsp;

Line 69 (and simillarly on line 120):

    #if defined __AVR_ATmega328P__  
    	  noTone(mPin);
    #endif // !	

    #if defined ESP32
	  ledcDetachPin(mPin);
    #endif // !	

to:

    #if defined ESP32
    	  ledcDetachPin(mPin);
    #else
      	  noTone(mPin);
    #endif // !

**Comment by evert-arias** [comment]
@mvackel Hi!
Done! https://github.com/evert-arias/EasyBuzzer/pull/7 Thank you for your collaboration 👍 
https://github.com/evert-arias/EasyBuzzer/releases/tag/v1.0.3

**Comment by evert-arias** [comment]
I will close this issue since it has been solved
